//! The programs the holodeck offers. Generated by scripts/build-exec-sources.mjs from
//! PROGRAM_CATALOG in model/catalog.mjs; do not edit.

use crate::world::Program;

#[rustfmt::skip]
pub const PROGRAMS: &[Program] = &[
    Program { program_id: 1, scene_id: "paint", name: "Paint", description: "A shared 2D canvas. Click to paint voxels everyone sees, live and persisted." },
];
